### ISSUE TITLE
Support for DBs without an Index

### ISSUE THREAD

**Issue by barncastle** [Warpten/DBClientFiles.NET#4]
Hopefully not a major implementation issue but WDBC and WDB2 don't necessarily have an Index constraint, for example pre-WotLK `CharBaseInfo`. The client handles this by generating Ids based on the record index on load. 

```C
struct CharBaseInfoRec // Alpha 0.5.3.3368
{
  char m_raceID;
  char m_classID;
  int m_proficiency;
  int m_generatedID; // not in file
};
```
P.S. Great work, I'll be using this for WDBX once write support is in!

**Comment by Warpten** [comment]
Thank you! I've put this off for months because I was burnt out on Wow (still kind of am).

This was fine for earlier builds since I did not have a key constraint on WDBC and WDB2 - I had to add it for `StorageDictionary` (the reflection call is a pain in the ass but I have no better idea).

I'll look into it more once I'm done-ish with the automapper

**Comment by Warpten** [comment]
Not sure about how to handle this - should I force the user to provide an [Index] field even when the file doesn't have one (and populate it myself) (which would be easier for me to deal with, like, a whole lot) - or should I just not care about index at all write some sort of polyfill to keep `StorageDictionary` alive?

**Comment by funjoker** [comment]
RowNumber = Index i would say.

**Comment by Warpten** [comment]
This is done out of the box now:

* `StorageDictionary<Key, Value>` forces you to provide a key getter.
* `StorageDictionary<T>` forces `T` to inherit `IKeyType`, and forces the key itself to `uint`
